version: '3'
services:
  app:
    build: .
    container_name: 'medical-clinic-app'
    depends_on:
      - 'postgres-db'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/medical-db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
    ports:
      - '8080:8080'
    networks:
      - my-network
  postgres-db:
    image: postgres
    container_name: 'postgres'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'medical-db'
    ports:
      - '5432:5432'
    networks:
      - my-network
  pgadmin_service:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: giljr.2009@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "15432:80"
    networks:
      - my-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  my-network:
    driver: bridge

volumes:
  pgadmin-data: